# Generated by Django 5.2.6 on 2025-09-23 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0003_aircraft_seat_seatassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_code', models.CharField(blank=True, max_length=5)),
                ('qr_code_data', models.CharField(blank=True, max_length=256)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_passes', to='flights.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_passes', to='flights.passenger')),
            ],
            options={
                'unique_together': {('flight', 'passenger')},
            },
        ),
    ]
