# Generated by Django 5.2.6 on 2025-09-23 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0003_aircraft_seat_seatassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrOpsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CANCEL', 'Cancellation'), ('DELAY', 'Delay')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irops_events', to='flights.flight')),
            ],
        ),
        migrations.CreateModel(
            name='ReaccommodationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('from_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaccom_from', to='flights.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaccom_suggestions', to='flights.passenger')),
                ('to_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaccom_to', to='flights.flight')),
            ],
        ),
    ]
