# Generated by Django 5.2.6 on 2025-09-23 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('range_nm', models.IntegerField(default=0)),
                ('seat_layout', models.CharField(help_text='e.g., 3-3 or custom layout code', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('letter', models.CharField(max_length=1)),
                ('cabin', models.CharField(default='MAIN', max_length=16)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.aircraft')),
            ],
            options={
                'unique_together': {('aircraft', 'row', 'letter')},
            },
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='CONFIRMED', max_length=16)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='flights.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='flights.passenger')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='flights.seat')),
            ],
            options={
                'unique_together': {('flight', 'seat')},
            },
        ),
    ]
